
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="Style.css">

    <title>Cupcakes</title>
</head>
<body>
<div class="container-fluid">
    <div class="row">

        <img class="img-fluid" src="images/Untitled.png" width="100%">

        <div class="col-lg-2"></div>
        <div class="col-lg-8 navbar-default">
            <nav class="navbar navbar-expand-lg navbar-light">
                <a class="navbar-brand" href="#"><img src="images/cupcake.png" width="30%"></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="ml-auto">
                    <div class="collapse navbar-collapse" id="navbarNavDropdown">
                        <form class="form-inline my-2 my-lg-0">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text" id="basic-addon1">@</span>
                                </div>
                                <input type="email" class="form-control mr-sm-2" placeholder="Username"
                                       aria-label="Username" aria-describedby="basic-addon1">
                                <input type="password" class="form-control mr-sm-2" placeholder="Password"
                                       aria-label="Password">
                                <input class="btn btn-success ml-1" type="submit" value="Submit">
                            </div>
                        </form>
                    </div>
                </div>
            </nav>
        </div>
        <div class="col-lg-2"></div>
    </div>
